<?php

namespace Bml\AppBundle\Entity;

use Doctrine\DBAL\LockMode;
use Doctrine\ORM\EntityRepository;

/**
 * AccountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccountRepository extends EntityRepository
{
    /**
     * @param mixed $id
     * @param int $lockMode
     * @param null $lockVersion
     * @return Account
     */
    public function find($id, $lockMode = LockMode::NONE, $lockVersion = null)
    {
        return parent::find($id, $lockMode, $lockVersion);
    }

    /**
     * @param float $minReferrerPayout
     * @return Account[]
     */
    public function findForReferrerPayout($minReferrerPayout)
    {
        return $this->createQueryBuilder('a')
            ->andWhere('a.totalUnpaidReferralEarnings >= :minReferrerPayout')
            ->andWhere('a.totalDeposit > 0')
            ->setParameter('minReferrerPayout', $minReferrerPayout)
            ->getQuery()
            ->getResult();
    }

}
