<?php

namespace Bml\AppBundle\Entity;

use Doctrine\DBAL\LockMode;
use Doctrine\ORM\EntityRepository;

/**
 * AccountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepositRepository extends EntityRepository
{
    /**
     * @return Deposit
     */
    public function findFirstUnpaid()
    {
        return $this->createQueryBuilder('d')
            ->orWhere('d.status = :status1')
            ->orWhere('d.status = :status2')
            ->orderBy('d.id', 'asc')
            ->setParameter('status1', Deposit::STATUS_CONFIRMED)
            ->setParameter('status2', Deposit::STATUS_READY_FOR_PAYOUT)
            ->setMaxResults(1)
            ->getQuery()
            ->getSingleResult();
    }

    /**
     * @param mixed $id
     * @param int $lockMode
     * @param null $lockVersion
     * @return Deposit
     */
    public function find($id, $lockMode = LockMode::NONE, $lockVersion = null)
    {
        return parent::find($id, $lockMode, $lockVersion);
    }

    /**
     * @return Deposit[]
     */
    public function findAll()
    {
        return parent::findAll();
    }

    /**
     * @param array $criteria
     * @param array $orderBy
     * @param null $limit
     * @param null $offset
     * @return Deposit[]
     */
    public function findBy(array $criteria, array $orderBy = null, $limit = null, $offset = null)
    {
        return parent::findBy($criteria, $orderBy, $limit, $offset);
    }

    /**
     * @param array $criteria
     * @param array $orderBy
     * @return Deposit
     */
    public function findOneBy(array $criteria, array $orderBy = null)
    {
        return parent::findOneBy($criteria, $orderBy);
    }


}
