<?php

namespace Bml\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AccountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PayoutRepository extends EntityRepository
{

    /**
     * @param Round $round
     * @param string $orderBy
     * @return Payout[]
     */
    public function findForPayout(Round $round, $orderBy = 'asc')
    {
        return $this->findBy(['paid' => false, 'readyForPayout' => true, 'round' => $round], ['id' => $orderBy]);
    }
}
